"""Optional browser smoke test: start server.py, then run with Playwright installed."""
import io
import os
from PIL import Image
from playwright.sync_api import sync_playwright, expect

BASE = os.environ.get('MTG_TEST_URL', 'http://127.0.0.1:8005')
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page(viewport={'width': 1440, 'height': 900})
    errors, chat_calls = [], []
    page.on('pageerror', lambda error: errors.append(str(error)))
    def chat(route):
        chat_calls.append(route.request.post_data_json)
        route.fulfill(json={'answer': 'Let’s talk about your ramp.'})
    page.route('**/api/chat', chat)
    page.goto(BASE)
    page.locator('#sidebar-add').click()
    page.wait_for_url('**/upload')
    page.locator('#deck-name').fill('Compact smoke deck')
    page.locator('#commander').fill('Omnath, Locus of Mana')
    page.locator('#list').fill('1 Omnath, Locus of Mana\n1 Sol Ring\n35 Forest\n63 Colossal Dreadmaw')
    image = io.BytesIO()
    Image.new('RGB', (80, 60), (120, 80, 190)).save(image, format='PNG')
    page.locator('#cover-file').set_input_files({'name': 'custom-art.png', 'mimeType': 'image/png', 'buffer': image.getvalue()})
    expect(page.locator('#import-error')).to_contain_text('Artwork selected')
    page.locator('#import-form button[type=submit]').click()
    page.locator('[data-tab=analyze]').click()
    page.wait_for_url('**/analyze')
    expect(page.locator('.gallery-card')).to_have_count(4)
    assert page.locator('#analysis-cover').get_attribute('src').startswith('data:image/jpeg;')
    page.locator('[data-view=text]').click()
    expect(page.locator('.text-card')).to_have_count(4)
    page.locator('[data-view=stats]').click()
    page.locator('#refresh-stats').click()
    expect(page.locator('#analysis-status')).to_contain_text('Card data refreshed', timeout=60000)
    expect(page.locator('#deck-browser')).to_contain_text('Seven-card opening hands')
    page.locator('[data-view=images]').click()
    page.locator('.gallery-card img').first.wait_for(state='visible')
    expect(page.locator('.gallery-card img').first).to_have_js_property('complete', True, timeout=30000)
    page.screenshot(path='/tmp/vibes-analysis.png', full_page=True)
    page.locator('[data-tab=play]').click()
    page.wait_for_url('**/playtest')
    expect(page.locator('#hand .card')).to_have_count(7)
    page.locator('#hand img').first.wait_for(state='visible', timeout=30000)
    assert page.locator('#hand img').first.evaluate('(image)=>image.naturalWidth>0')
    assert page.locator('#hand').bounding_box()['y'] + page.locator('#hand').bounding_box()['height'] <= 900
    page.locator('#hand .card').first.drag_to(page.locator('#battlefield'))
    expect(page.locator('#battlefield .table-card')).to_have_count(1)
    expect(page.locator('#hand .card')).to_have_count(6)
    page.locator('#battlefield .table-card').first.hover()
    page.keyboard.press('t')
    expect(page.locator('#battlefield .tapped')).to_have_count(1)
    page.locator('#battlefield .table-card').first.hover()
    page.keyboard.press('g')
    expect(page.locator('#graveyard .table-card')).to_have_count(1)
    page.locator('#graveyard .table-card').first.drag_to(page.locator('[data-drop=exile]'))
    expect(page.locator('#exile .table-card')).to_have_count(1)
    page.locator('#exile .table-card').first.hover()
    page.keyboard.press('l')
    expect(page.locator('#exile .table-card')).to_have_count(0)
    page.locator('#library-draw').click()
    expect(page.locator('#hand .card')).to_have_count(7)
    page.locator('#hand .card').first.hover()
    page.keyboard.press('p')
    expect(page.locator('#battlefield .table-card')).to_have_count(1)
    page.screenshot(path='/tmp/vibes-table.png', full_page=True)
    page.locator('[data-tab=chat]').click()
    page.wait_for_url(BASE + '/')
    page.locator('#prompt').fill('Help me improve my mana.')
    page.locator('#chat-form button').click()
    expect(page.locator('#messages')).to_contain_text('Let’s talk about your ramp.')
    assert 'coverData' not in chat_calls[-1]['context']['deck']
    page.screenshot(path='/tmp/vibes-libby.png', full_page=True)
    for width, height in [(1440, 900), (1366, 768), (390, 844)]:
        page.set_viewport_size({'width': width, 'height': height})
        page.locator('[data-tab=play]').click()
        page.wait_for_url('**/playtest')
        assert page.evaluate('document.documentElement.scrollHeight<=innerHeight'), (width, height, 'vertical overflow')
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth'), (width, height, 'horizontal overflow')
        hand = page.locator('#hand').bounding_box()
        assert hand['y'] + hand['height'] <= height
    page.screenshot(path='/tmp/vibes-mobile.png', full_page=True)
    assert not errors, errors
    print('Artwork upload/persistence, image/text/statistics views, live card images, drag/drop to four zones, hover hotkeys, AI context, and desktop/mobile fitted layouts passed.')
    browser.close()
